name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21'

#    - name: Grant execute permission for setup script
#      run: chmod +x setup.sh
#
#    - name: Run setup script
#      run: ./setup.sh

    - name: Build with Gradle
      run: cd extractor &&  ./gradlew clean build

    - name: Check git changes
      run: ./github/worflows/commands.sh git-diff
