name: CI/CD for DiffTool

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ] 
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: '21'
      CONFIG_DIR: '.ci-config'
      POM_URL: "https://raw.githubusercontent.com/checkstyle/test-configs/f08a12ee4dc34892b0438d1f69f447ed8db2c60c/checkstyle-tester/pom.xml"
      DIFF_TOOL_VERSION: "1.0-SNAPSHOT-all"
      PATCH_DIFF_TOOL_VERSION: "0.1-SNAPSHOT"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: checkstyle-gsoc/test-configs
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true
          fetch-depth: 1

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-

      - name: Build with Gradle
        run: |
          cd diff-java-tool
          ./gradlew clean build

      - name: Run Unit Tests
        run: |
          cd diff-java-tool
          ./gradlew test

      - name: Setup checkstyle-tester environment
        run: |
          echo "Current working directory:"
          pwd
          echo "Contents of current directory:"
          ls -la

          # Create checkstyle-tester directory
          mkdir -p checkstyle-tester
          cd checkstyle-tester

          # Download pom.xml
          curl --fail-with-body -L -o pom.xml "${{ env.POM_URL }}"

          # Create necessary subdirectories
          mkdir -p src/main/java
          mkdir -p repositories
          mkdir -p reports/diff

          echo "Verifying directory structure:"
          ls -R

          cd ..

      - name: Download DiffTool JAR
        uses: robinraju/release-downloader@v1.8
        with:
          repository: "relentless-pursuit/test-configs"
          tag: "diff-java-tool-${{ env.DIFF_TOOL_VERSION }}"
          fileName: "diff-java-tool-${{ env.DIFF_TOOL_VERSION }}.jar"
          out-file-path: "checkstyle-tester"

      - name: Download patch-diff-report-tool JAR
        uses: robinraju/release-downloader@v1.8
        with:
          repository: "checkstyle/contribution"
          tag: "patch-diff-report-tool-${{ env.PATCH_DIFF_TOOL_VERSION }}"
          fileName: >-
            patch-diff-report-tool-${{ env.PATCH_DIFF_TOOL_VERSION }}-jar-with-dependencies.jar
          out-file-path: "checkstyle-tester"

      - name: Prepare and Execute DiffTool
        run: |
          cd checkstyle-tester
          echo "Contents of checkstyle-tester directory:"
          ls -la

          # Define variables
          CHECKSTYLE_TESTER_DIR="${{ github.workspace }}/checkstyle-tester"
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            PR_BRANCH="${{ github.head_ref }}"
          else
            PR_BRANCH="master"
          fi
          REPO="${{ github.workspace }}/checkstyle"
          CONFIG_XML="${{ github.workspace }}/${{ env.CONFIG_DIR }}/config.xml"
          PROJECTS_PROPERTIES="${{ github.workspace }}/${{ env.CONFIG_DIR }}/project.properties"
          DIFFTOOL_JAR="diff-java-tool-${{ env.DIFF_TOOL_VERSION }}.jar"

          # Log variables
          echo "PR_BRANCH: $PR_BRANCH"
          echo "REPO: $REPO"
          echo "CONFIG_XML: $CONFIG_XML"
          echo "PROJECTS_PROPERTIES: $PROJECTS_PROPERTIES"
          echo "DIFFTOOL_JAR: $DIFFTOOL_JAR"

          # Clone checkstyle repository if not exists
          if [ ! -d "$REPO/.git" ]; then
            echo "Cloning checkstyle repository into $REPO"
            git clone https://github.com/checkstyle/checkstyle.git "$REPO" || { echo "Failed to clone repository"; exit 1; }
          fi

          # Fetch the default branch
          cd "$REPO" || { echo "Failed to change directory to $REPO"; exit 1; }
          echo "Fetching default branch"
          git fetch origin || { echo "Failed to fetch from origin"; exit 1; }
          DEFAULT_BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@') || { echo "Failed to get default branch"; exit 1; }
          echo "Default branch: $DEFAULT_BRANCH"

          # Return to the checkstyle-tester directory
          cd "$CHECKSTYLE_TESTER_DIR" || { echo "Failed to return to checkstyle-tester directory"; exit 1; }

          # Ensure reports/diff directory exists and is not empty
          mkdir -p reports/diff
          if [ ! "$(ls -A reports/diff)" ]; then
            echo "reports/diff is empty, creating dummy file"
            touch reports/diff/dummy.txt
          fi

          # Run DiffTool in 'diff' mode
          echo "Running DiffTool.jar in 'diff' mode"
          java -jar "$DIFFTOOL_JAR" \
            --localGitRepo "$REPO" \
            --baseBranch "master" \
            --baseConfig "$CONFIG_XML" \
            --patchBranch "$PR_BRANCH" \
            --patchConfig "$CONFIG_XML" \
            --listOfProjects "$PROJECTS_PROPERTIES" || { echo "DiffTool execution failed"; exit 1; }

          # Check contents of reports directory after execution
          echo "Contents of reports directory after DiffTool execution:"
          ls -R reports

      - name: Execute DiffTool.jar with Invalid Arguments
        run: |
          cd checkstyle-tester
          DIFFTOOL_JAR="diff-java-tool-${{ env.DIFF_TOOL_VERSION }}.jar"
          echo "Running DiffTool.jar with invalid arguments"
          java -jar "$DIFFTOOL_JAR" --invalidArg || echo "Handled invalid arguments gracefully"

      - name: Verify DiffTool Execution
        run: |
          echo "DiffTool executed successfully."

      - name: Upload Build Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: |
            diff-java-tool/build/reports
            diff-java-tool/build/test-results
            checkstyle-tester/reports
            checkstyle-tester/patch-diff-report-tool-${{ env.PATCH_DIFF_TOOL_VERSION }}-jar-with-dependencies.jar

      - name: Cleanup Temporary Files
        if: always()
        run: |
          rm -rf checkstyle-tester
