name: CI/CD for DiffTool

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: '21'
      CONFIG_DIR: '.ci-config'
      POM_URL: "https://raw.githubusercontent.com/checkstyle/test-configs/f08a12ee4dc34892b0438d1f69f447ed8db2c60c/checkstyle-tester/pom.xml"
      DIFF_TOOL_VERSION: "1.0-SNAPSHOT-all"
      PATCH_DIFF_TOOL_VERSION: "0.1-SNAPSHOT"

    steps:
      # 1. Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Set up JDK 21
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'

      # 3. Cache Maven dependencies
      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-

      # 4. Build the project with Gradle
      - name: Build with Gradle
        run: |
          cd diff-java-tool
          ./gradlew clean build

      # 5. Run unit tests
      - name: Run Unit Tests
        run: |
          cd diff-java-tool
          ./gradlew test

      - name: Create checkstyle-tester directory
        run: mkdir -p .ci-temp/test-configs/checkstyle-tester

      - name: Download pom.xml
        run: |
          mkdir -p .ci-temp/test-configs/checkstyle-tester
          curl --fail-with-body -L -o \
          .ci-temp/test-configs/checkstyle-tester/pom.xml "${{ env.POM_URL }}"

      - name: Download DiffTool JAR
        uses: robinraju/release-downloader@v1.8
        with:
          repository: "checkstyle/test-configs"
          tag: "diff-java-tool-${{ env.DIFF_TOOL_VERSION }}"
          fileName: "diff-java-tool-${{ env.DIFF_TOOL_VERSION }}.jar"
          out-file-path: ".ci-temp/test-configs/checkstyle-tester"

      - name: Download patch-diff-report-tool JAR
        uses: robinraju/release-downloader@v1.8
        with:
          repository: "checkstyle/contribution"
          tag: "patch-diff-report-tool-${{ env.PATCH_DIFF_TOOL_VERSION }}"
          fileName: >-
            patch-diff-report-tool-${{ env.PATCH_DIFF_TOOL_VERSION }}-jar-with-dependencies.jar
          out-file-path: ".ci-temp/test-configs/checkstyle-tester"
          
      # 11. Execute DiffTool.jar in 'diff' mode
      - name: Execute DiffTool.jar in Diff Mode
        run: |
          cd .ci-temp/test-configs/checkstyle-tester
          
          # Define necessary variables
          PR_BRANCH="${{ github.head_ref }}"  # For pull requests
          REPO="${{ github.workspace }}/checkstyle"
          BASE_BRANCH="upstream/master"
          CONFIG_XML="${{ github.workspace }}/${{ env.CONFIG_DIR }}/config.xml"
          PROJECTS_PROPERTIES="${{ github.workspace }}/${{ env.CONFIG_DIR }}/projects.properties"
          DIFFTOOL_JAR="diff-java-tool-${{ env.DIFF_TOOL_VERSION }}.jar"

          # Ensure the localGitRepo exists
          if [ ! -d "$REPO/.git" ]; then
            git clone https://github.com/checkstyle/checkstyle.git "$REPO"
          fi

          # Run DiffTool in 'diff' mode
          java -jar "$DIFFTOOL_JAR" \
            --localGitRepo "$REPO" \
            --baseBranch "$BASE_BRANCH" \
            --baseConfig "$CONFIG_XML" \
            --patchBranch "$PR_BRANCH" \
            --patchConfig "$CONFIG_XML" \
            --listOfProjects "$PROJECTS_PROPERTIES"

      # 12. Execute DiffTool.jar in 'single' mode
      - name: Execute DiffTool.jar in Single Mode
        run: |
          cd .ci-temp/test-configs/checkstyle-tester

          # Define necessary variables
          PR_BRANCH="${{ github.head_ref }}"  # For pull requests
          REPO="${{ github.workspace }}/checkstyle"
          CONFIG_XML="${{ github.workspace }}/${{ env.CONFIG_DIR }}/config.xml"
          PROJECTS_PROPERTIES="${{ github.workspace }}/${{ env.CONFIG_DIR }}/projects.properties"
          DIFFTOOL_JAR="diff-java-tool-${{ env.DIFF_TOOL_VERSION }}.jar"

          # Run DiffTool in 'single' mode
          java -jar "$DIFFTOOL_JAR" \
            --localGitRepo "$REPO" \
            --patchBranch "feature/single-mode" \  # Adjust as needed
            --patchConfig "$CONFIG_XML" \
            --listOfProjects "$PROJECTS_PROPERTIES" \
            --mode single
            
      # 8. Execute DiffTool.jar with invalid arguments to print help
      - name: Execute DiffTool.jar with Invalid Arguments
        run: |
          java -jar "$DIFFTOOL_JAR" --invalidArg

      # 9. Download Patch Diff Report Tool
      - name: Download Patch Diff Report Tool
        uses: actions/download-artifact@v3
        with:
          name: patch-diff-report-tool
          path: .ci-temp/patch-diff-report-tool

      # 10. Verify no exceptions occurred during DiffTool execution
      - name: Verify DiffTool Execution
        run: |
          # This step is implicitly handled by previous steps. If any step fails, the job fails.
          echo "DiffTool executed successfully."

      # 11. Upload build reports and logs on failure
      - name: Upload Build Reports on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: |
            diff-java-tool/build/reports
            diff-java-tool/build/test-results
            .ci-temp/patch-diff-report-tool

      # 12. Cleanup (optional)
      - name: Cleanup Temporary Files
        if: always()
        run: |
          rm -rf .ci-temp

